# Write your MySQL query statement below
SELECT PRICES.PRODUCT_ID,IFNULL(ROUND(SUM(PRICES.PRICE*UNITSSOLD.UNITS)/SUM(UNITSSOLD.UNITS),2),0) AS average_price FROM
PRICES LEFT JOIN UNITSSOLD
ON PRICES.PRODUCT_ID=UNITSSOLD.PRODUCT_ID
AND UNITSSOLD.PURCHASE_DATE BETWEEN PRICES.START_DATE AND PRICES.END_DATE
GROUP BY PRICES.PRODUCT_ID;